t-runner: Fix warning
tools/test-runner.c:1363:6: error: no previous declaration for
‘test_stat_queue_entry_destroy’ [-Werror=missing-declarations]
 void test_stat_queue_entry_destroy(void *data)